Package.swift

https://docs.ditto.live/changelog
Depends on getditto/DittoObjC#1

🔖 Version 1.1.0

---

Package.swift

Waiting for getditto/ditto#5100 to complete.

🔖 Release 1.1.2

---

Package.swift

Waiting on getditto/ditto#5210

🔖 Release 1.1.3

---

Package.swift

Updated Swift package for [DittoSwift](https://github.com/CocoaPods/Specs/commit/6925b433ea1be6a8b360dee93ca6df6268194def) and [DittoObjC](https://github.com/CocoaPods/Specs/commit/98516deb860a830cc6221ed0dc75ef321afd8518) 1.1.4 release.
Part of getditto/ditto#5262

🔖 Release 1.1.4

---

Package.swift

Updated Swift package for [DittoSwift](https://github.com/CocoaPods/Specs/commit/9e17e7cd926e5b32ce551ac955580226893afe78) and [DittoObjC](https://github.com/CocoaPods/Specs/commit/17453622280fe77513854d26b7d3ead87a40a3d8) 1.1.5 release.

🔗 Update links and hashes for 1.1.5 artifacts

---

Package.swift

[DittoObjC](https://github.com/CocoaPods/Specs/commit/5b355658b24da1a07abe4cb69b3ee5743e84b45d) and [DittoSwift](https://github.com/CocoaPods/Specs/commit/017c9a21e6ccb0da9679919ac2b35dd69bd90b70) 1.1.6 release

🔖 Release 1.1.6

---

Package.swift

Swift package update for [DittoSwift](https://github.com/CocoaPods/Specs/commit/a1fc368e8e619e04e1214a25a8bdc98fa68f43ba) and [DittoObjC](https://github.com/CocoaPods/Specs/commit/835fd91031f6c2d65de5e6d41c05ffc821dd1bc7)

 🔗 Update URLs and hashes for 1.1.7 artifacts

---

README.md

https://swiftpackageindex.com/getditto/DittoSwiftPackage/information-for-package-maintainers
https://swiftpackageindex.com/getditto/DittoSwiftPackage

📛 Add Swift Package Index badges to readme

---

Package.swift
Sources/DittoSwiftWrapper/dummy.swift

Initial implementation of getditto/dito#5366
Hopefully, this fixes getditto/ditto#6489

🎯 Add DittoSwiftWrapper target

---

Package.swift

Experimental release with one addition:
- 🔊 Added use case hints to log messages emitted for slow or deadlocked write transactions getditto/ditto#7409

🔖 Version 3.0.3-alpha1

---

Package.swift

https://github.com/getditto/DittoSwiftPackage/releases/tag/4.4.4

🔖 Release 4.4.4

---

README.md

Changed contact email to support@ditto.live.

📧 Update contact email

---

Package.swift

Related to getditto/ditto#12507
This PR updates the `Package.swift` manifest URLs and checksums for the [4.7.1-rc.1](https://github.com/getditto/DittoSwiftPackage/releases/tag/4.7.1-rc.1) artifacts.

🔖 Release 4.7.1-rc.1

---

Package.swift

Updating package manifest from release getditto/ditto#12535

🔖 Release 4.7.1-rc.2

---

Package.swift

🔖 Release 4.7.1

---

Package.swift

Updating `Package.swift` from [4.7.2-rc.1](https://github.com/getditto/DittoSwiftPackage/releases/tag/4.7.2-rc.1) release

🔖 Release 4.7.2-rc.1

---

Package.swift

Release 4.9.1

---

Package.swift

🔖 Version 4.9.2

---

Package.swift

🔖 Version 4.9.3-rc.1

---

Package.swift

🔖 Version 4.9.3

---

Package.swift

🔖 Version 4.9.4-rc.1

---

Package.swift

🔖 Version 4.9.4

---

Package.swift

🔖 Version 4.10.0-rc.1

---

Package.swift

🔖 Version 4.10.0-rc.2

---

Package.swift

🔖 Version 4.10.0

---

Package.swift

🔖 Version 4.10.2-rc.1

---

Package.swift

🔖 Version 4.10.1

---

Package.swift

🔖 Version 4.10.2-preview.1

---

Package.swift

🔖 Version 4.10.2

---

Package.swift

🔖 Version 4.11.0-preview.2

---

Package.swift

🔖 Version 4.11.0-preview.4

---

Package.swift

🔖 Version 4.11.0-rc.1

---

Package.swift

🔖 Version 4.11.0-rc.2

---

Package.swift

🔖 Version 4.11.0-rc.4

---

Package.swift

🔖 Version 4.12.0-experimental-publishing.1

---

Package.swift

🔖 Version 4.10.5

---

Package.swift

🔖 Version 4.11.1-preview.1

---

Package.swift

🔖 Version 4.11.1

---

Package.swift

🔖 Version 4.11.2-preview.1

---

Package.swift

🔖 Version 4.12.0-preview.1

---

Package.swift

🔖 Version 4.12.0-experimental-untangle.0

---

Package.swift

🔖 Version 4.11.2

---

Package.swift

🔖 Version 4.12.0-preview.3

---

Package.swift

🔖 Version 4.12.0-rc.1

---

Package.swift

🔖 Version 4.12.0-experimental-js-persistence-directory.1

---

Package.swift

🔖 Version 4.11.3-rc.1

---

Package.swift

🔖 Version 5.0.0-experimental.kb-inline-objc-into-swift-sdk.1

---

Package.swift

🔖 Version 4.12.0

---

Package.swift

🔖 Version 4.11.4-rc.1

---

Package.swift

🔖 Version 4.11.4

---

Package.swift

🔖 Version 4.12.1-rc.1

---

Package.swift

🔖 Version 5.0.0-experimental.kb-inline-objc-into-swift-sdk.5

---

Package.swift

🔖 Version 4.11.5-rc.1

---

Package.swift

🔖 Version 5.0.0-swift-6.1

---

Package.swift

🔖 Version 5.0.0-experimental.swift-6.2

---

Package.swift

🔖 Version 4.12.2-experimental-bp-receive-timeout-3

---

Package.swift

🔖 Version 4.11.5

---

Package.swift

🔖 Version 4.12.2

---

Package.swift

🔖 Version 4.12.2-experimental.bp-receive-timeout.5

---

Package.swift

🔖 Version 4.12.3-rc.1
